name: CD

permissions:
  contents: write

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Backend Image Tag
        run: |
          sed -i "s/tag:.*/tag: ${GITHUB_SHA}/" helm/skillpulse-chart/values.yaml

      - name: Commit Updated values.yaml
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add helm/skillpulse-chart/values.yaml

          git commit -m "Update image tag to ${GITHUB_SHA}" || echo "No changes to commit"

          git push

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-2 --name skillpulse-cluster

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Deploy to EKS using Helm
        run: |
          helm upgrade --install skillpulse ./helm/skillpulse-chart --namespace skillpulse --create-namespace
